update_config=1
# country=US

network={
    ssid="YOUR_SSID_HERE"    # <-- Replace with your Wi-Fi SSID
    psk="YOUR_PSK_HERE"      # <-- Replace with your Wi-Fi password or use a hashed PSK from wpa_passphrase
    key_mgmt=WPA-PSK
}
